### ISSUE TITLE
自动测试中，器件下拉/选择列表过窄，名称显示不全

### ISSUE THREAD

**Issue by cheng1214** [SiP-HFUT/Sip-automatic_probe_station#1]
问题：自动测试的器件标签导入后，器件下拉/选择列表过窄，导致一些具有较长名称的器件显示不全。
横向拉长软件的窗口无法解决问题。
解决办法：修改相关的GUI代码，增加列表宽度

**Comment by DingChunfjw** [comment]
将autoMeasurePanel 的175行 
self.checkList.InsertColumn(0, 'Device', width=150) 
的width修改为150（原来为100）可以增加选择列表的宽度

**Comment by DingChunfjw** [comment]
将instrumentFrame 的93行改为hbox.Add(MotorVbox,proportion=1)
