### ISSUE TITLE
8个功率计端口全部开启后，软件窗口显示问题

### ISSUE THREAD

**Issue by cheng1214** [SiP-HFUT/Sip-automatic_probe_station#3]
当8个功率计端口全部开启后，软件窗口是否过于拥挤？能否正常显示？
若OK，可以直接这里回复，然后关闭这个issue
若不行，需要修改相关GUI代码（能用即可）

**Comment by yfz1999** [comment]
目前的显示屏比之前老电脑的显示情况要好，看八个没有问题；尺寸已经改小一些，不过甚至不改感觉新显示器视野也还好，可以看到log。
