### ISSUE TITLE
修复bug：GUI中的光谱显示图，无法使用放大按钮

### ISSUE THREAD

**Issue by cheng1214** [SiP-HFUT/Sip-automatic_probe_station#8]
显示错误如下图所示：

![fig](https://github.com/SiP-HFUT/Sip-automatic_probe_station/assets/35131910/dce17668-94f7-4ba3-af01-9c0ae5d64e4c)

**Comment by yfz1999** [comment]
comment

**Comment by cheng1214** [comment]
fixed in 6243464af979176cd9a3a5a3ae00839d4615e6ec
